### ISSUE TITLE
Sometimes after it is connecting and loading into the main app, the loading transparency overlay will remain, and everything will be grey

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerAir#5] opened 2019-04-16 05:58 UTC
I had this happen twice on my iPhone and once on my iPad: https://i.imgur.com/C5kUCYo.png

**Comment by J2Kbr** [comment] 2019-06-19 10:07
Also happened with me few times. After researching, turned out the issue is with the Qt Framework used by Gtuner Air (not with my code). Soon I will be updating the framework version and expect/hope this to be fixed. I am closing this issue as there is nothing I can do on the Gtuner Air source code to fix.

**Closed as completed by J2Kbr** 2019-06-19 10:07 UTC
Labels: question
